name: CEconomy
version: 1.0
author: Tim Nawratil
depend: [Vault]

main: de.craftq.tim.economy.CEconomy

commands:
  money:
    aliases: [bal, balance]
  pay:
  setmoney:
  addmoney:
  moneytop:
    aliases: [baltop]